### ISSUE TITLE
visualizing MGE parameter studies

### ISSUE THREAD

**Issue by rachelslaybaugh** [rachelslaybaugh/RQI_MGE#11]
(1) I am not sure the difference between
- parameter-study-visualization
- RQI-Multilevel-Parameters
they have the same description at the top. Are they using the same data? Do we only need one for making the image we want in the paper? Please update the notes at the top (if we're going to cite the repo for reproducibility, we want it all to be super clear).

(2) for the visualization notebook, I get this error:
AttributeError                            Traceback (most recent call last)
<ipython-input-3-df6336a603d5> in <module>()
      4 relaxwt = ['0.8', '1.0', '1.2']
      5 df = np.zeros((3,3,3,3))
----> 6 for k,v in solve_times.iteritems():
      7     c = k.split('-')
      8     ss = c[1].strip('ss')

AttributeError: 'dict' object has no attribute 'iteritems'

(3) This is an MGE parameter  study, not RQI :)
I can change the name, but didn't want to add more confusion at this moment.

**Comment by marissachanlatte** [comment]
1) RQI-Multilevel-Parameters is the repo Tara made to figure out which were the ideal parameters. The parameter-study-visualization notebook is my notebook producing a plot to visualize the data. They use the same data, but run independently, so we only need the visualization notebook to get the plot. I updated the description at the top.

2) I wasn't able to reproduce the error message. Can you confirm you're running the latest version? Or are you using python 3? iteritems got dropped in python 3. If that's the problem, I can rewrite it to work either way. 

3) You can go ahead and change that if you'd like.

**Comment by rachelslaybaugh** [comment]
1. ok. I am still have the problem of not quite knowing what was run with what and how to figure it out. I'll use runner.py to get all the right info about specs. 

What machine was this run on and where can I find machine specs?

2. I tried with both 2 and 3. same error. brand new versions of anaconda in both cases. For the time being I can just resave a copy of the plot without the title on it.

**Comment by marissachanlatte** [comment]
1. That's probably a question for @sphamil or Tara. It looks like it was run on cades, but I'm not sure. 

2. Can you show me before/after group meeting on Thursday, and I'll try to figure out what's going on?

**Comment by rachelslaybaugh** [comment]
1. Ah. ok. I think so. I think also 289 cores? 

Remind me, what is subspace size? Is that the number of z blocks? 

2. yes.
